// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'recive.model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'recive.model.g.dart';

enum DifficultyLevel { easy, intermediate, advanced }

@freezed
class Recive with _$Recive {
  const factory Recive({
    required String title,
    required CreatorSummary creatorSummary,
    required Origin origin,
    required List<Ingredient> ingredients,
    required List<InstructionStep> instructions,
    required DifficultyLevel difficultyLevel,
    required int preparationTimeMinute,
    required int cookingTimeMinute,
    required String serving,
    required String cuisineType,
    required int calories,
    required List<String> imageUrls,
    required List<String> tags,
    required List<Allergen> allergens,
    required String source,
    required List<String> variations,
  }) = _Recive;

  factory Recive.fromJson(Map<String, Object?> json) => _$ReciveFromJson(json);
}

@freezed
class Allergen with _$Allergen {
  const factory Allergen({
    required String name,
    required String infoLink,
  }) = _Allergen;
  factory Allergen.fromJson(Map<String, Object?> json) =>
      _$AllergenFromJson(json);
}

@freezed
class Ingredient with _$Ingredient {
  const factory Ingredient({
    required double amount,
    required String measurement,
    required String svgIcon,
    required String name,
  }) = _Ingredient;
  factory Ingredient.fromJson(Map<String, Object?> json) =>
      _$IngredientFromJson(json);
}

@freezed
class InstructionStep with _$InstructionStep {
  const factory InstructionStep({
    required String name,
    required String description,
    required int preparationTimeMinute,
    required List<String> imageUrls,
  }) = _InstructionStep;
  factory InstructionStep.fromJson(Map<String, Object?> json) =>
      _$InstructionStepFromJson(json);
}

@freezed
class CreatorSummary with _$CreatorSummary {
  const factory CreatorSummary({
    required String firstName,
    required String lastName,
    required String imageUrl,
  }) = _CreatorSummary;
  factory CreatorSummary.fromJson(Map<String, Object?> json) =>
      _$CreatorSummaryFromJson(json);
}

@freezed
class Origin with _$Origin {
  const factory Origin({
    required String code,
    required String country,
    required String state,
    required String city,
    required String title,
  }) = _Origin;

  factory Origin.fromJson(Map<String, Object?> json) => _$OriginFromJson(json);
}
