// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzIBdmpa8YZcD6s9Y2yK2MK5rsyjQcRfc',
    appId: '1:240113539356:web:24dccbd1d88817eca682d9',
    messagingSenderId: '240113539356',
    projectId: 'vancouverartcompass-c73df',
    authDomain: 'vancouverartcompass-c73df.firebaseapp.com',
    storageBucket: 'vancouverartcompass-c73df.firebasestorage.app',
    measurementId: 'G-YL08H565NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJrJRclxIsDKKZlOhtVJ6oXB26Y4hzBFk',
    appId: '1:240113539356:android:703ee33272872bb6a682d9',
    messagingSenderId: '240113539356',
    projectId: 'vancouverartcompass-c73df',
    storageBucket: 'vancouverartcompass-c73df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRQt36A9xcZSgcCDpPKqnaUZ8QBoipgnY',
    appId: '1:240113539356:ios:561cca642d7d680fa682d9',
    messagingSenderId: '240113539356',
    projectId: 'vancouverartcompass-c73df',
    storageBucket: 'vancouverartcompass-c73df.firebasestorage.app',
    androidClientId: '240113539356-v41momddqk6tr1tksh8kd1ob611e9954.apps.googleusercontent.com',
    iosClientId: '240113539356-h0tv8qjf1s0rfv24hhajk5eks162gvhu.apps.googleusercontent.com',
    iosBundleId: 'mrzg.vancouverartcompass.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRQt36A9xcZSgcCDpPKqnaUZ8QBoipgnY',
    appId: '1:240113539356:ios:561cca642d7d680fa682d9',
    messagingSenderId: '240113539356',
    projectId: 'vancouverartcompass-c73df',
    storageBucket: 'vancouverartcompass-c73df.firebasestorage.app',
    androidClientId: '240113539356-v41momddqk6tr1tksh8kd1ob611e9954.apps.googleusercontent.com',
    iosClientId: '240113539356-h0tv8qjf1s0rfv24hhajk5eks162gvhu.apps.googleusercontent.com',
    iosBundleId: 'mrzg.vancouverartcompass.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzIBdmpa8YZcD6s9Y2yK2MK5rsyjQcRfc',
    appId: '1:240113539356:web:22537d3544544971a682d9',
    messagingSenderId: '240113539356',
    projectId: 'vancouverartcompass-c73df',
    authDomain: 'vancouverartcompass-c73df.firebaseapp.com',
    storageBucket: 'vancouverartcompass-c73df.firebasestorage.app',
    measurementId: 'G-7W56E67YSP',
  );
}
