// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAswmUsVak3c3WX2DEGE-oWiwnEStGOKtk',
    appId: '1:337988051792:web:15829bded4d25cbe6f0255',
    messagingSenderId: '337988051792',
    projectId: 'recive-mzg',
    authDomain: 'recive-mzg.firebaseapp.com',
    storageBucket: 'recive-mzg.appspot.com',
    measurementId: 'G-B33F9D9X36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2NHhlVq8vQba2PwlABaeOpkmFy5LbKBg',
    appId: '1:337988051792:android:2bd4ec1612bce0fe6f0255',
    messagingSenderId: '337988051792',
    projectId: 'recive-mzg',
    storageBucket: 'recive-mzg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmaTbzEzC59qeAurCa4jq3Q67j7Q14Zv0',
    appId: '1:337988051792:ios:8ca7bf24cc1720796f0255',
    messagingSenderId: '337988051792',
    projectId: 'recive-mzg',
    storageBucket: 'recive-mzg.appspot.com',
    androidClientId: '337988051792-8okrjd30qr9g107au45cemm0b2amhsir.apps.googleusercontent.com',
    iosClientId: '337988051792-kpjg0sn1h9b2f972a5q79u0lt24o6p3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.recive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmaTbzEzC59qeAurCa4jq3Q67j7Q14Zv0',
    appId: '1:337988051792:ios:64f395a675ba885e6f0255',
    messagingSenderId: '337988051792',
    projectId: 'recive-mzg',
    storageBucket: 'recive-mzg.appspot.com',
    androidClientId: '337988051792-8okrjd30qr9g107au45cemm0b2amhsir.apps.googleusercontent.com',
    iosClientId: '337988051792-3c8472umals3bqc32m0dqrhctjnteagt.apps.googleusercontent.com',
    iosBundleId: 'com.example.recive.RunnerTests',
  );
}
